export interface Course {
  id: string;
  title: string;
  description: string;
  author: string;
  durationInMinutes: number;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  technologies: string[];
  language: 'English' | 'Spanish' | 'German';
  rating: number; // 1 to 5
  imageUrl: string;
}

export const ALL_COURSES: Course[] = [
  {
    id: '1',
    title: 'Angular Fundamentals',
    description:
      'Learn the basics of Angular, including components, templates, and services.',
    author: 'Jane Doe',
    durationInMinutes: 120,
    level: 'Beginner',
    technologies: ['Angular'],
    language: 'English',
    rating: 4.8,
    imageUrl: 'https://placehold.co/300x180/angular1.png',
  },
  {
    id: '2',
    title: 'React for Beginners',
    description: 'A comprehensive introduction to React and its core concepts.',
    author: 'John Smith',
    durationInMinutes: 90,
    level: 'Beginner',
    technologies: ['React'],
    language: 'English',
    rating: 4.5,
    imageUrl: 'https://placehold.co/300x180/react1.png',
  },
  {
    id: '3',
    title: 'Advanced Angular Patterns',
    description: 'Master advanced Angular topics and best practices.',
    author: 'Jane Doe',
    durationInMinutes: 180,
    level: 'Advanced',
    technologies: ['Angular'],
    language: 'English',
    rating: 4.9,
    imageUrl: 'https://placehold.co/300x180/angular2.png',
  },
  {
    id: '4',
    title: 'Vue.js Essentials',
    description: 'Get started with Vue.js and build dynamic web apps.',
    author: 'Carlos Ruiz',
    durationInMinutes: 110,
    level: 'Intermediate',
    technologies: ['Vue'],
    language: 'Spanish',
    rating: 4.3,
    imageUrl: 'https://placehold.co/300x180/vue1.png',
  },
  {
    id: '5',
    title: 'TypeScript Deep Dive',
    description: 'Explore advanced TypeScript features for large-scale apps.',
    author: 'Anna Müller',
    durationInMinutes: 140,
    level: 'Advanced',
    technologies: ['TypeScript'],
    language: 'German',
    rating: 4.7,
    imageUrl: 'https://placehold.co/300x180/typescript1.png',
  },
  {
    id: '6',
    title: 'React Hooks in Depth',
    description: 'Understand and use React Hooks effectively.',
    author: 'John Smith',
    durationInMinutes: 100,
    level: 'Intermediate',
    technologies: ['React'],
    language: 'English',
    rating: 4.6,
    imageUrl: 'https://placehold.co/300x180/react2.png',
  },
  {
    id: '7',
    title: 'Angular Signals Explained',
    description: 'A practical guide to using Signals in Angular.',
    author: 'Jane Doe',
    durationInMinutes: 80,
    level: 'Intermediate',
    technologies: ['Angular'],
    language: 'English',
    rating: 4.4,
    imageUrl: 'https://placehold.co/300x180/angular3.png',
  },
  {
    id: '8',
    title: 'Fullstack with Node & Angular',
    description: 'Build a fullstack app using Node.js and Angular.',
    author: 'Carlos Ruiz',
    durationInMinutes: 200,
    level: 'Advanced',
    technologies: ['Angular', 'Node.js'],
    language: 'Spanish',
    rating: 4.8,
    imageUrl: 'https://placehold.co/300x180/fullstack1.png',
  },
  {
    id: '9',
    title: 'React State Management',
    description: 'Learn Redux and Context API for managing state in React.',
    author: 'John Smith',
    durationInMinutes: 130,
    level: 'Intermediate',
    technologies: ['React', 'Redux'],
    language: 'English',
    rating: 4.2,
    imageUrl: 'https://placehold.co/300x180/react3.png',
  },
  {
    id: '10',
    title: 'Angular Testing Masterclass',
    description: 'Write robust unit and integration tests for Angular apps.',
    author: 'Anna Müller',
    durationInMinutes: 150,
    level: 'Advanced',
    technologies: ['Angular', 'Jasmine'],
    language: 'German',
    rating: 4.9,
    imageUrl: 'https://placehold.co/300x180/angular4.png',
  },
  {
    id: '11',
    title: 'Vue.js for Beginners',
    description: 'A beginner-friendly introduction to Vue.js.',
    author: 'Carlos Ruiz',
    durationInMinutes: 75,
    level: 'Beginner',
    technologies: ['Vue'],
    language: 'Spanish',
    rating: 4.1,
    imageUrl: 'https://placehold.co/300x180/vue2.png',
  },
  {
    id: '12',
    title: 'JavaScript Essentials',
    description: 'Master the fundamentals of JavaScript.',
    author: 'Jane Doe',
    durationInMinutes: 95,
    level: 'Beginner',
    technologies: ['JavaScript'],
    language: 'English',
    rating: 4.3,
    imageUrl: 'https://placehold.co/300x180/js1.png',
  },
  {
    id: '13',
    title: 'React Performance Optimization',
    description: 'Techniques to make your React apps faster.',
    author: 'John Smith',
    durationInMinutes: 105,
    level: 'Advanced',
    technologies: ['React'],
    language: 'English',
    rating: 4.7,
    imageUrl: 'https://placehold.co/300x180/react4.png',
  },
  {
    id: '14',
    title: 'Angular Forms & Validation',
    description: 'Build robust forms with Angular and validate user input.',
    author: 'Jane Doe',
    durationInMinutes: 115,
    level: 'Intermediate',
    technologies: ['Angular'],
    language: 'English',
    rating: 4.5,
    imageUrl: 'https://placehold.co/300x180/angular5.png',
  },
  {
    id: '15',
    title: 'TypeScript for React Developers',
    description: 'Use TypeScript to write safer React code.',
    author: 'Anna Müller',
    durationInMinutes: 90,
    level: 'Intermediate',
    technologies: ['TypeScript', 'React'],
    language: 'German',
    rating: 4.6,
    imageUrl: 'https://placehold.co/300x180/typescript2.png',
  },
  {
    id: '16',
    title: 'Vue.js Advanced Techniques',
    description: 'Take your Vue.js skills to the next level.',
    author: 'Carlos Ruiz',
    durationInMinutes: 125,
    level: 'Advanced',
    technologies: ['Vue'],
    language: 'Spanish',
    rating: 4.4,
    imageUrl: 'https://placehold.co/300x180/vue3.png',
  },
  {
    id: '17',
    title: 'JavaScript ES2021 Features',
    description: 'Learn the latest features in modern JavaScript.',
    author: 'Jane Doe',
    durationInMinutes: 85,
    level: 'Intermediate',
    technologies: ['JavaScript'],
    language: 'English',
    rating: 4.2,
    imageUrl: 'https://placehold.co/300x180/js2.png',
  },
  {
    id: '18',
    title: 'Testing React Apps',
    description:
      'Write tests for React components using Jest and React Testing Library.',
    author: 'John Smith',
    durationInMinutes: 100,
    level: 'Intermediate',
    technologies: ['React', 'Jest'],
    language: 'English',
    rating: 4.5,
    imageUrl: 'https://placehold.co/300x180/react5.png',
  },
  {
    id: '19',
    title: 'Node.js Crash Course',
    description: 'A quick introduction to Node.js for web developers.',
    author: 'Carlos Ruiz',
    durationInMinutes: 70,
    level: 'Beginner',
    technologies: ['Node.js'],
    language: 'Spanish',
    rating: 4.0,
    imageUrl: 'https://placehold.co/300x180/node1.png',
  },
  {
    id: '20',
    title: 'Angular RxJS in Practice',
    description: 'Master reactive programming in Angular with RxJS.',
    author: 'Jane Doe',
    durationInMinutes: 160,
    level: 'Advanced',
    technologies: ['Angular', 'RxJS'],
    language: 'English',
    rating: 4.8,
    imageUrl: 'https://placehold.co/300x180/angular6.png',
  },
];
